import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { handleOwnerPasswordAuth, withOwnerPasswordPrincipal, handleOwnerPasswordBrowserGate, ownerPasswordAuthHealth } from '../src/crm-owner-password-auth.mjs';

const ALLOW_LIMITER={limit:async()=>({success:true})};
const DENY_LIMITER={limit:async()=>({success:false})};
const ENV={CRM_OWNER_AUTH_MODE:'hybrid',CRM_OWNER_PASSWORD:'correct-horse-battery-staple',CRM_OWNER_SESSION_SECRET:'test-session-secret-32-bytes-minimum-value',CRM_OWNER_LOGIN_RATE_LIMITER:ALLOW_LIMITER};
const PASSWORD_ENV={...ENV,CRM_OWNER_AUTH_MODE:'password'};
const LOGIN='https://crm.example.test/__crm/owner-login';
function formRequest(password,env=ENV,extraHeaders={}){return new Request(LOGIN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','origin':'https://crm.example.test',...extraHeaders},body:new URLSearchParams({password:password??env.CRM_OWNER_PASSWORD})})}
const HANDOFF_HEADERS={'x-internal-token':'reservation-secret','x-crm-internal-principal':'reservation-app','x-crm-handoff-base-path':'/customer-management'};

test('default access mode keeps password login disabled',async()=>{const res=await handleOwnerPasswordAuth(new Request(LOGIN),{CRM_OWNER_PASSWORD:'x',CRM_OWNER_SESSION_SECRET:'y'});assert.equal(res.status,503);assert.match(await res.text(),/Cloudflare Access/)});
test('invalid nonempty auth mode fails closed and strips spoofed owner identity',async()=>{const invalid={...ENV,CRM_OWNER_AUTH_MODE:'pasword'};const login=await handleOwnerPasswordAuth(new Request(LOGIN),invalid);assert.equal(login.status,503);const req=await withOwnerPasswordPrincipal(new Request('https://crm.example.test/admin',{headers:{'cf-access-authenticated-user-email':'ohw3rz5578d277e@gmail.com','x-user-email':'ohw3rz5578d277e@gmail.com'}}),invalid);assert.equal(req.headers.get('cf-access-authenticated-user-email'),null);assert.equal(req.headers.get('x-user-email'),null);const gate=handleOwnerPasswordBrowserGate(req,invalid);assert.equal(gate.status,503);const health=ownerPasswordAuthHealth(invalid);assert.equal(health.owner_password_auth_mode,'invalid');assert.equal(health.owner_password_auth_mode_valid,false);assert.equal(health.owner_password_auth_enabled,false)});
test('password auth fails closed when secrets are not configured',async()=>{const res=await handleOwnerPasswordAuth(new Request(LOGIN),{CRM_OWNER_AUTH_MODE:'password'});assert.equal(res.status,503);assert.match(await res.text(),/まだ有効化されていません/)});
test('password mode fails closed when rate limit binding is missing',async()=>{const res=await handleOwnerPasswordAuth(formRequest(ENV.CRM_OWNER_PASSWORD),{...ENV,CRM_OWNER_AUTH_MODE:'password',CRM_OWNER_LOGIN_RATE_LIMITER:undefined});assert.equal(res.status,503);assert.equal((await res.json()).error,'owner_password_rate_limit_not_configured')});
test('hybrid mode also fails closed when rate limit binding is missing',async()=>{const env={...ENV,CRM_OWNER_LOGIN_RATE_LIMITER:undefined};const res=await handleOwnerPasswordAuth(formRequest(env.CRM_OWNER_PASSWORD,env),env);assert.equal(res.status,503);assert.equal((await res.json()).error,'owner_password_rate_limit_not_configured');assert.equal(ownerPasswordAuthHealth(env).owner_password_auth_enabled,false)});
test('password-only mode rejects rate-limited login before password validation',async()=>{const env={...PASSWORD_ENV,CRM_OWNER_LOGIN_RATE_LIMITER:DENY_LIMITER};const res=await handleOwnerPasswordAuth(formRequest(env.CRM_OWNER_PASSWORD,env),env);assert.equal(res.status,429);assert.equal((await res.json()).error,'rate_limited')});
test('hybrid mode rejects rate-limited login before password validation',async()=>{const env={...ENV,CRM_OWNER_LOGIN_RATE_LIMITER:DENY_LIMITER};const res=await handleOwnerPasswordAuth(formRequest(env.CRM_OWNER_PASSWORD,env),env);assert.equal(res.status,429);assert.equal((await res.json()).error,'rate_limited')});
test('wrong password is rejected without issuing session cookie',async()=>{const res=await handleOwnerPasswordAuth(formRequest('wrong-password'),ENV);assert.equal(res.status,401);assert.equal(res.headers.get('set-cookie'),null)});
test('cross-origin login is rejected',async()=>{const req=new Request(LOGIN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','origin':'https://evil.example'},body:new URLSearchParams({password:ENV.CRM_OWNER_PASSWORD})});const res=await handleOwnerPasswordAuth(req,ENV);assert.equal(res.status,403)});
test('correct password creates a strict secure HttpOnly owner session',async()=>{const res=await handleOwnerPasswordAuth(formRequest(ENV.CRM_OWNER_PASSWORD),ENV);assert.equal(res.status,303);assert.equal(res.headers.get('location'),'/admin');const cookie=res.headers.get('set-cookie')||'';assert.match(cookie,/crm_owner_session=/);assert.match(cookie,/HttpOnly/i);assert.match(cookie,/Secure/i);assert.match(cookie,/SameSite=Strict/i);assert.match(cookie,/Max-Age=43200/i)});
test('valid owner session maps only to canonical owner principal',async()=>{const login=await handleOwnerPasswordAuth(formRequest(ENV.CRM_OWNER_PASSWORD),ENV);const cookie=(login.headers.get('set-cookie')||'').split(';')[0];const req=new Request('https://crm.example.test/admin',{headers:{cookie}});const effective=await withOwnerPasswordPrincipal(req,ENV);assert.equal(effective.headers.get('cf-access-authenticated-user-email'),'ohw3rz5578d277e@gmail.com');assert.equal(effective.headers.get('x-crm-owner-auth'),'password-session')});
test('tampered owner session is never elevated',async()=>{const login=await handleOwnerPasswordAuth(formRequest(ENV.CRM_OWNER_PASSWORD),ENV);const raw=(login.headers.get('set-cookie')||'').split(';')[0];const [name,value='']=raw.split('=');const [payload,signature]=value.split('.');assert.ok(payload&&signature);const tamperedPayload=(payload.startsWith('A')?'B':'A')+payload.slice(1);const req=new Request('https://crm.example.test/admin',{headers:{cookie:`${name}=${tamperedPayload}.${signature}`}});const effective=await withOwnerPasswordPrincipal(req,ENV);assert.equal(effective.headers.get('cf-access-authenticated-user-email'),null)});
test('hybrid mode preserves existing Cloudflare Access principal',async()=>{const req=new Request('https://crm.example.test/admin',{headers:{'cf-access-authenticated-user-email':'existing@example.com','x-crm-owner-auth':'spoofed'}});const effective=await withOwnerPasswordPrincipal(req,ENV);assert.equal(effective.headers.get('cf-access-authenticated-user-email'),'existing@example.com');assert.equal(effective.headers.get('x-crm-owner-auth'),null)});
test('password-only mode strips all spoofed owner identity headers without a valid session',async()=>{const req=new Request('https://crm.example.test/admin',{headers:{'cf-access-authenticated-user-email':'ohw3rz5578d277e@gmail.com','cf-access-user-email':'ohw3rz5578d277e@gmail.com','x-user-email':'ohw3rz5578d277e@gmail.com','x-crm-owner-auth':'password-session'}});const effective=await withOwnerPasswordPrincipal(req,PASSWORD_ENV);assert.equal(effective.headers.get('cf-access-authenticated-user-email'),null);assert.equal(effective.headers.get('cf-access-user-email'),null);assert.equal(effective.headers.get('x-user-email'),null);assert.equal(effective.headers.get('x-crm-owner-auth'),null)});
test('password-only mode accepts signed session after stripping spoofable headers',async()=>{const login=await handleOwnerPasswordAuth(formRequest(PASSWORD_ENV.CRM_OWNER_PASSWORD,PASSWORD_ENV),PASSWORD_ENV);const cookie=(login.headers.get('set-cookie')||'').split(';')[0];const req=new Request('https://crm.example.test/admin',{headers:{cookie,'cf-access-authenticated-user-email':'attacker@example.com','x-user-email':'attacker@example.com'}});const effective=await withOwnerPasswordPrincipal(req,PASSWORD_ENV);assert.equal(effective.headers.get('cf-access-authenticated-user-email'),'ohw3rz5578d277e@gmail.com');assert.equal(effective.headers.get('x-user-email'),null);assert.equal(effective.headers.get('x-crm-owner-auth'),'password-session')});
test('password-only browser entry redirects unauthenticated owner to login',async()=>{const req=await withOwnerPasswordPrincipal(new Request('https://crm.example.test/admin'),PASSWORD_ENV);const res=handleOwnerPasswordBrowserGate(req,PASSWORD_ENV);assert.equal(res.status,302);assert.equal(res.headers.get('location'),'/__crm/owner-login')});
test('password-only browser gate preserves authenticated Reservation internal handoff',async()=>{const env={...PASSWORD_ENV,CRM_INTERNAL_TOKEN:'reservation-secret'};const req=await withOwnerPasswordPrincipal(new Request('https://crm.example.test/admin',{headers:{'x-internal-token':'reservation-secret','x-crm-internal-principal':'reservation-app'}}),env);assert.equal(handleOwnerPasswordBrowserGate(req,env),null)});
test('Reservation handoff login page posts inside proxy namespace',async()=>{const env={...PASSWORD_ENV,CRM_INTERNAL_TOKEN:'reservation-secret'};const req=new Request(LOGIN,{headers:HANDOFF_HEADERS});const res=await handleOwnerPasswordAuth(req,env);assert.equal(res.status,200);assert.match(await res.text(),/action="\/customer-management\/__crm\/owner-login"/)});
test('Reservation handoff rejected login keeps retry form inside proxy namespace',async()=>{const env={...PASSWORD_ENV,CRM_INTERNAL_TOKEN:'reservation-secret'};const req=formRequest('wrong-password',env,HANDOFF_HEADERS);const res=await handleOwnerPasswordAuth(req,env);assert.equal(res.status,401);assert.match(await res.text(),/action="\/customer-management\/__crm\/owner-login"/)});
test('password logout clears owner cookie and returns to owner login',async()=>{const req=new Request('https://crm.example.test/__crm/owner-logout',{method:'POST',headers:{origin:'https://crm.example.test'}});const res=await handleOwnerPasswordAuth(req,PASSWORD_ENV);assert.equal(res.status,303);assert.equal(res.headers.get('location'),'/__crm/owner-login');assert.match(res.headers.get('set-cookie')||'',/Max-Age=0/)});
test('Reservation handoff password logout stays inside proxy namespace',async()=>{const env={...PASSWORD_ENV,CRM_INTERNAL_TOKEN:'reservation-secret'};const req=new Request('https://crm.example.test/__crm/owner-logout',{method:'POST',headers:{origin:'https://crm.example.test',...HANDOFF_HEADERS}});const res=await handleOwnerPasswordAuth(req,env);assert.equal(res.status,303);assert.equal(res.headers.get('location'),'/customer-management/__crm/owner-login');assert.match(res.headers.get('set-cookie')||'',/Max-Age=0/)});
test('access logout clears owner cookie and preserves Cloudflare Access logout flow',async()=>{const env={CRM_OWNER_AUTH_MODE:'access'};const req=new Request('https://crm.example.test/__crm/owner-logout',{method:'POST',headers:{origin:'https://crm.example.test','cf-access-authenticated-user-email':'owner@example.com'}});const res=await handleOwnerPasswordAuth(req,env);assert.equal(res.status,303);assert.match(res.headers.get('location')||'',/^\/cdn-cgi\/access\/logout\?returnTo=/);assert.match(res.headers.get('set-cookie')||'',/Max-Age=0/)});
test('wrangler declares canonical owner login rate limiter binding',()=>{const config=JSON.parse(fs.readFileSync('wrangler.jsonc','utf8'));const limiter=(config.ratelimits||[]).find(x=>x.name==='CRM_OWNER_LOGIN_RATE_LIMITER');assert.ok(limiter);assert.match(String(limiter.namespace_id),/^\d+$/);assert.equal(limiter.simple.limit,10);assert.equal(limiter.simple.period,60)});
test('health contract confirms auth adds no D1/customer-id/LINE write path',()=>{const h=ownerPasswordAuthHealth(PASSWORD_ENV);assert.equal(h.owner_password_auth_supported,true);assert.equal(h.owner_password_auth_mode,'password');assert.equal(h.owner_password_auth_mode_valid,true);assert.equal(h.owner_password_auth_configured,true);assert.equal(h.owner_password_auth_enabled,true);assert.equal(h.owner_password_auth_fail_closed,true);assert.equal(h.owner_password_auth_header_spoof_protection,true);assert.equal(h.owner_password_auth_rate_limit_required,true);assert.equal(h.owner_password_auth_rate_limit_configured,true);assert.equal(h.owner_password_auth_reservation_internal_preserved,true);assert.equal(h.owner_password_auth_logout_post_endpoint,true);assert.equal(h.owner_password_auth_access_logout_preserved,true);assert.equal(h.owner_password_auth_customer_id_generation,false);assert.equal(h.owner_password_auth_d1_write,false);assert.equal(h.owner_password_auth_line_send,false)});
