import assert from 'node:assert/strict';
import {buildMemberFamilyPassIntegrationReadModel as rawBuildMemberFamilyPassIntegrationReadModel,buildProspectMemberIntegrationReadModel} from '../src/member-family-pass-integration-read-model.mjs';
const mid='MID_abcdefghijklmnopqrstuvwxyz123456',pid='PID_abcdefghijklmnopqrstuvwxyz123456';
const buildMemberFamilyPassIntegrationReadModel=(args={})=>rawBuildMemberFamilyPassIntegrationReadModel({persisted_member_identity_id:args.member_identity_id,persisted_family_customer_id:args.canonical_customer_id,persisted_memory_count_family_id:args.family_id,persisted_durable_black_family_id:args.family_id,durable_black_entitlement:false,...args});
let r=buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,durable_black_entitlement:false,entitlement_schema_applied:true});
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-2',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'family_link_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',persisted_family_customer_id:'87654321',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'family_link_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,persisted_memory_count_family_id:'FAM-2',entitlement_schema_applied:true}).status,'memory_count_family_not_verified');
// FAMILY_BINDING_MISMATCH_REGRESSION
assert.equal(r.status,'ready');
assert.equal(r.family_pass.current_tier,'BLACK');
assert.equal(r.family_pass.black_currently_qualified,true);
assert.equal(r.black_contract.threshold,10);
assert.equal(r.black_contract.photo_goods_discount_percent,10);
assert.equal(r.black_contract.shooting_fee_discount,false);
assert.equal(r.black_contract.automatic_award,false);
assert.equal(r.write_allowed,false);
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:false,member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'family_link_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:false,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'member_customer_binding_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'87654321',member_status:'active',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'member_customer_binding_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_identity_id:'MID_zyxwvutsrqponmlkjihgfedcba654321',persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'member_customer_binding_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'prospect',published_non_deleted_memory_count:10,entitlement_schema_applied:true}).status,'member_status_not_eligible');
for(const missing of [undefined,null,'','   ',false]) assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:missing,entitlement_schema_applied:true}).status,'missing_memory_count_evidence');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10}).status,'entitlement_schema_evidence_required');
assert.equal(rawBuildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',persisted_family_customer_id:'12345678',member_customer_binding_verified:true,persisted_member_identity_id:mid,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,persisted_memory_count_family_id:'FAM-1',entitlement_schema_applied:true}).status,'durable_black_evidence_required');
assert.equal(rawBuildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',persisted_family_customer_id:'12345678',member_customer_binding_verified:true,persisted_member_identity_id:mid,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,persisted_memory_count_family_id:'FAM-1',entitlement_schema_applied:true,durable_black_entitlement:1}).status,'durable_black_evidence_required');
r=buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,durable_black_entitlement:false,entitlement_schema_applied:false});
assert.equal(r.status,'ready');
assert.equal(r.family_pass.black_lifetime_persistence_supported,false);
for(const malformed of [['10'],{value:10},10n]) assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:malformed,entitlement_schema_applied:true}).status,'invalid_memory_count');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:0,durable_black_entitlement:true,entitlement_schema_applied:false}).status,'durable_black_schema_conflict');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:0,durable_black_entitlement:true,entitlement_schema_applied:true,persisted_durable_black_family_id:'FAM-2',black_achieved_at:'2026-10-07T00:00:00Z',durable_black_qualifying_memory_count:10}).status,'durable_black_family_not_verified');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:0,durable_black_entitlement:true,entitlement_schema_applied:true}).status,'invalid_durable_black_evidence');
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:0,durable_black_entitlement:true,entitlement_schema_applied:true,black_achieved_at:'2026-10-07T00:00:00Z',durable_black_qualifying_memory_count:9}).status,'invalid_durable_black_evidence');
const durableBlack=buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:0,durable_black_entitlement:true,entitlement_schema_applied:true,black_achieved_at:'2026-10-07T00:00:00Z',durable_black_qualifying_memory_count:10});
assert.equal(durableBlack.status,'ready');
assert.equal(durableBlack.family_pass.black_lifetime_entitled,true);
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:'9'.repeat(400),entitlement_schema_applied:true}).status,'invalid_memory_count');
r=buildProspectMemberIntegrationReadModel({member_identity_id:mid,prospect_id:pid,persisted_member_identity_id:mid,persisted_prospect_id:pid,member_prospect_binding_verified:true,consent_current:true,signup_benefit_state:'available',acquisition_source:'instagram'});
assert.equal(r.status,'ready');
assert.equal(r.canonical_customer_id,null);
assert.equal(r.family_pass,null);
assert.equal(r.memories,null);
assert.equal(r.prospect_access_to_customer_memories,false);
assert.equal(r.customer_id_generation,false);
for(const malformed of [false,['0'],{value:0},0n,'9'.repeat(400),Number.MAX_SAFE_INTEGER+1]){
 assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:1,entitlement_schema_applied:true,review_pending_count:malformed}).status,'invalid_review_count');
 assert.equal(buildProspectMemberIntegrationReadModel({member_identity_id:mid,prospect_id:pid,persisted_member_identity_id:mid,persisted_prospect_id:pid,member_prospect_binding_verified:true,review_pending_count:malformed}).status,'invalid_review_count');
}
console.log('MEMBER_FAMILY_PASS_INTEGRATION_READ_MODEL=PASS');
console.log('BLACK_THRESHOLD=10');
console.log('BLACK_PHOTO_GOODS_DISCOUNT_PERCENT=10');
console.log('BLACK_SHOOTING_FEE_DISCOUNT=0');
console.log('PROSPECT_CUSTOMER_MEMORY_ACCESS=0');
console.log('PRODUCTION_WRITE=0');

// DURABLE_BLACK_SCHEMA_FALSE_REGRESSION
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:10,durable_black_entitlement:true,entitlement_schema_applied:false,black_achieved_at:'2026-01-01T00:00:00Z',durable_black_qualifying_memory_count:10}).status,'durable_black_schema_conflict');

// DURABLE_BLACK_VALID_EVIDENCE_REGRESSION
const validDurableBlack=buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,persisted_verified_family_id:'FAM-1',member_customer_binding_verified:true,persisted_member_customer_id:'12345678',member_status:'active',published_non_deleted_memory_count:9,durable_black_entitlement:true,entitlement_schema_applied:true,black_achieved_at:'2026-01-01T00:00:00Z',durable_black_qualifying_memory_count:10});
assert.equal(validDurableBlack.status,'ready');
assert.equal(validDurableBlack.family_pass.black_lifetime_entitled,true);
assert.equal(validDurableBlack.black_contract.shooting_fee_discount,false);

assert.equal(buildProspectMemberIntegrationReadModel({member_identity_id:mid,prospect_id:pid}).status,'member_prospect_binding_not_verified');
assert.equal(buildProspectMemberIntegrationReadModel({member_identity_id:mid,prospect_id:pid,persisted_member_identity_id:mid,persisted_prospect_id:'PID_zyxwvutsrqponmlkjihgfedcba654321',member_prospect_binding_verified:true}).status,'member_prospect_binding_not_verified');
