import assert from 'node:assert/strict';
import {buildMemberFamilyPassIntegrationReadModel,buildProspectMemberIntegrationReadModel} from '../src/member-family-pass-integration-read-model.mjs';
const mid='MID_abcdefghijklmnopqrstuvwxyz123456',pid='PID_abcdefghijklmnopqrstuvwxyz123456';
let r=buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:true,published_non_deleted_memory_count:10,durable_black_entitlement:false});
assert.equal(r.status,'ready');
assert.equal(r.family_pass.current_tier,'BLACK');
assert.equal(r.family_pass.black_currently_qualified,true);
assert.equal(r.black_contract.threshold,10);
assert.equal(r.black_contract.photo_goods_discount_percent,10);
assert.equal(r.black_contract.shooting_fee_discount,false);
assert.equal(r.black_contract.automatic_award,false);
assert.equal(r.write_allowed,false);
assert.equal(buildMemberFamilyPassIntegrationReadModel({member_identity_id:mid,canonical_customer_id:'12345678',family_id:'FAM-1',family_link_verified:false,published_non_deleted_memory_count:10}).status,'family_link_not_verified');
r=buildProspectMemberIntegrationReadModel({member_identity_id:mid,prospect_id:pid,consent_current:true,signup_benefit_state:'available',acquisition_source:'instagram'});
assert.equal(r.status,'ready');
assert.equal(r.canonical_customer_id,null);
assert.equal(r.family_pass,null);
assert.equal(r.memories,null);
assert.equal(r.prospect_access_to_customer_memories,false);
assert.equal(r.customer_id_generation,false);
console.log('MEMBER_FAMILY_PASS_INTEGRATION_READ_MODEL=PASS');
console.log('BLACK_THRESHOLD=10');
console.log('BLACK_PHOTO_GOODS_DISCOUNT_PERCENT=10');
console.log('BLACK_SHOOTING_FEE_DISCOUNT=0');
console.log('PROSPECT_CUSTOMER_MEMORY_ACCESS=0');
console.log('PRODUCTION_WRITE=0');
