import assert from 'node:assert/strict';
import {planMemberPiiPurgeReconciliation} from '../src/member-d1-pii-purge-reconciliation-plan.mjs';
const now=Date.UTC(2026,9,8),day=86400000;
const expired={record_id:'rec_1',pii_written_at_ms:now-31*day,pii_present:true,google_synced:false,identity_verified:false,version_verified:false};
const plan=planMemberPiiPurgeReconciliation({rows:[expired],now_ms:now});
assert.equal(plan.status,'reconciliation_planned');
assert.equal(plan.execution_allowed,false);
assert.equal(plan.items.length,1);
assert.equal(plan.items[0].needs_deadline_recovery,true);
assert.equal(plan.items[0].reconciliation_state,'PENDING_EXECUTION');
assert.equal(planMemberPiiPurgeReconciliation({rows:[{...expired,record_id:'rec_2',identity_verified:'true'}],now_ms:now}).status,'invalid_record_evidence');
