import assert from 'node:assert/strict';
import {CLEAN_MEMBER_STACK_ORIGINS,CLEAN_MEMBER_STACK_BASE,validateCleanMemberStackOrigins} from '../src/member-clean-stack-provenance.mjs';
assert.equal(CLEAN_MEMBER_STACK_BASE,'9d282bc2c1906379f33b7d0d8d28604c26cc3881');
const good=CLEAN_MEMBER_STACK_ORIGINS.map(([pr,head])=>({pr,head,review_threads_resolved:true}));
let r=validateCleanMemberStackOrigins(good);
assert.equal(r.status,'provenance_verified');
assert.equal(r.production_ready,false);
assert.equal(r.merge_allowed,false);
r=validateCleanMemberStackOrigins(good.map(x=>x.pr===210?{...x,head:'0'.repeat(40)}:x));
assert.equal(r.status,'blocked');
r=validateCleanMemberStackOrigins(good.map(x=>x.pr===211?{...x,review_threads_resolved:false}:x));
assert.equal(r.status,'blocked');
r=validateCleanMemberStackOrigins([...good.slice(0,2),null,...good.slice(3)]);
assert.equal(r.status,'blocked');
assert.equal(r.reason,'invalid_origin_evidence');
r=validateCleanMemberStackOrigins(good.map(x=>x.pr===203?{...x,pr:'203'}:x));
assert.equal(r.status,'blocked');
assert.equal(r.reason,'invalid_origin_evidence');
r=validateCleanMemberStackOrigins([...good.slice(0,-1),{...good[0]}]);
assert.equal(r.status,'blocked');
assert.equal(r.reason,'duplicate_origin_evidence');
console.log('MEMBER_CLEAN_STACK_PROVENANCE=PASS');
console.log('BASE_PR_202_HEAD='+CLEAN_MEMBER_STACK_BASE);
console.log('MALFORMED_ORIGIN_EVIDENCE=BLOCKED');
console.log('TYPED_PR_EVIDENCE=REQUIRED');
console.log('PRODUCTION_READY=0');
console.log('MERGE_ALLOWED=0');
